runtime: nodejs20

env_variables:
  NODE_ENV: production
  PORT: 8080
  SESSION_SECRET: your-secure-session-secret-here
  RATE_LIMIT_WINDOW: 15
  RATE_LIMIT_MAX: 100

automatic_scaling:
  min_instances: 0  # Scale to 0 when not in use (saves money)
  max_instances: 1  # Keep it minimal for free tier
  target_cpu_utilization: 0.6

# Use smallest instance for free tier
instance_class: F1

# Skip files that don't need to be deployed
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?tests?/.*$
- ^(.*/)?test_.*\.js$
- ^(.*/)?.*_test\.js$
- node_modules/
